sudo: false

language: rust
rust: nightly

after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    cargo doc &&
    echo '<meta http-equiv=refresh content=0;url=mo-gc/index.html>' > target/doc/index.html &&
    pip install --user ghp-import &&
    ghp-import -n target/doc &&
    git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
